#!/usr/bin/env bash
# One-time setup so CouchUI can be started without cd-ing into the project
# or remembering npm commands.
#
# Installs:
#   * a `couchui` command on your PATH  -> start it from any terminal
#   * a desktop entry                    -> start it from the app menu
#
# Run once:  ./setup-shortcuts.sh
# Both point at wherever this project currently lives, so re-run it if you
# ever move the folder.

set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
DESKTOP_DIR="$HOME/.local/share/applications"
ICON_DIR="$HOME/.local/share/icons"

mkdir -p "$BIN_DIR" "$DESKTOP_DIR" "$ICON_DIR"

# ---- `couchui` command ----
cat > "$BIN_DIR/couchui" << EOF
#!/usr/bin/env bash
# Generated by setup-shortcuts.sh — points at the CouchUI install.
cd "$APP_DIR" && exec npm start "\$@"
EOF
chmod +x "$BIN_DIR/couchui"
echo "Installed command: $BIN_DIR/couchui"

# ---- desktop entry ----
cat > "$DESKTOP_DIR/couch-ui.desktop" << EOF
[Desktop Entry]
Name=CouchUI
Comment=Controller-first kiosk launcher for the living room
Exec=$BIN_DIR/couchui
Path=$APP_DIR
Terminal=false
Type=Application
Categories=AudioVideo;Player;
StartupWMClass=CouchUI
EOF
chmod +x "$DESKTOP_DIR/couch-ui.desktop"
echo "Installed desktop entry: $DESKTOP_DIR/couch-ui.desktop"

# Refresh the menu so it shows up without logging out.
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$DESKTOP_DIR" >/dev/null 2>&1 || true
fi

echo
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
  echo "NOTE: $BIN_DIR isn't on your PATH yet. Add it with:"
  echo
  echo "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc && source ~/.bashrc"
  echo
fi
echo "Done. Start CouchUI by typing:  couchui"
echo "...or find CouchUI in your application menu."
